### ISSUE TITLE
Compatibility with Garmin Fenix 7

### ISSUE THREAD

**Issue by risa** [dliedke/Meditate#1]
Hi, I have used this app on Fenix 6 and loved it. However, after upgrading to Fenix 7, it is no longer compatible, and I miss it! And I am not alone, obviously - lots of people are asking for the Fenix 7 compatibility on the app page: https://apps.garmin.com/en-US/apps/1cc98099-c08b-4fc7-91e6-0f3615a3ab2c

Is it just a build setting or is more necessary? Can we help somehow?

**Comment by risa** [comment]
Oops, sorry, it is the old one and you are publishing a new one. Sorry for the confusion!

**Comment by dliedke** [comment]
Hi @risa ! Sorry about the confusion, you are correct.

I republished the Meditate updated application for newer watch models to this URL:

https://apps.garmin.com/en-US/apps/c5fc5ea5-7d12-4fb9-be9c-701663a39db7

Also simpler version for other watches with less memory:

Forerunner® 235:
https://apps.garmin.com/en-US/apps/2f6378a0-09b3-402c-8553-366639fa73fd

Instinct® 2 /  Instinct® 2S / Instinct® Crossover:
https://apps.garmin.com/en-US/apps/45829a6e-f247-4261-9ae6-8587f557f397

Thanks a lot and enjoy the Meditate application! 🙏
