### ISSUE TITLE
Feature request: automatic DND mode for the time of meditation

### ISSUE THREAD

**Issue by SkyWheel** [dliedke/Meditate#10]
Hello and thanks for the great app!
Not sure if it's possible, but it would be nice to have a feature that automatically turns on Do Not Disturb mode for the time of meditation sessions, then after finishing turns it off.
Sometimes I forget to turn DND mode on, and then a notification comes to my phone in the middle of the session. Then sometimes I forget to turn DND mode off 😅
Mettā

**Comment by dliedke** [comment]
Appreciate your nice review @SkyWheel , but the watch can't control the phone sound, unless we had an app running on the phone that would receive the message and that would be too much complicated. Please set your phone to silent manually. Thank you! 🙏

**Comment by SkyWheel** [comment]
> Appreciate your nice review @SkyWheel , but the watch can't control the phone sound, unless we had an app running on the phone that would receive the message and that would be too much complicated. Please set your phone to silent manually. Thank you! 🙏

Sorry, I wasn't clear enough: I wasn't talking about phone's DND mode, I was talking about the Garmin watch DND mode.

**Comment by dliedke** [comment]
From Claude Sonnet 3.5

To answer your question accurately, I'll need to provide some context about Garmin watches and their features.
Garmin watches typically have a Do Not Disturb (DND) mode, which can be activated to silence notifications and alerts. However, the ability for a third-party Garmin app to directly control the DND mode is limited.
As of my last update in April 2024, Garmin's Connect IQ platform, which allows for third-party app development, does not provide direct API access for apps to control system-level features like DND mode. This means that a standard Garmin app cannot directly set the watch's DND mode.
That said, there are a few related possibilities:

Garmin's own Connect app: The official Garmin Connect mobile app can control various settings on the watch, including DND mode, when the watch is connected to the phone via Bluetooth.
Scheduled DND: Many Garmin watches allow you to set a schedule for DND mode directly on the watch or through the Garmin Connect app.
Custom watch faces or widgets: While they can't directly control DND, some custom watch faces or widgets might be able to provide shortcuts to quickly access the DND setting on the watch.
Future updates: Garmin could potentially expand the capabilities available to third-party developers in future updates to their Connect IQ platform.

If you're looking for a way to easily control your Garmin watch's DND mode, I'd recommend using the official Garmin Connect app or setting up a schedule directly on your watch.

Sorry!
