### ISSUE TITLE
Activity title does not contain time on Forerunner 255

### ISSUE THREAD

**Issue by robcsi** [dliedke/Meditate#11]
Hello,

I reported this on the Connect-Iq page of the application as well, but I cannot further reply there to continue the conversation.

So, the issue is that I set '[time]', 'Meditation [time]', 'M [time]', without quotation marks in the settings and still, the activity names don't contain the time durations.
These combinations all result in 'Meditation' only being set as title. Even if the second combination would exceed the characters limit, the others don't.

What could be the problem?
Thanks

**Comment by dliedke** [comment]
Hello, are you using Garmin Express with watch connected via USB to update the activity time in Meditate app?

When updating with Connect IQ mobile it does not work properly.

Thanks!

**Comment by robcsi** [comment]
No, I'm not using the Express app, I don't have a Windows machine.

I set it via the Connect IQ mobile app, as that's the only one with which this can be configured for the FR255. On my previous watch, Fenix 6 Pro, it was possible to configure the app via the Connect mobile application also, without opening Connect IQ.

So it means Connect IQ is the problem? I'll try it on a Windows machine then...

**Comment by robcsi** [comment]
It doesn't work with the Express app either. I set to 'M [time]', and I still get Meditation only all the time.

**Comment by dliedke** [comment]
ok, thanks for testing, but I can't reproduce it on my watch. Maybe you can try with VS code and Garmin SDK to troubleshoot with your device. Sorry about that!

git clone https://github.com/dliedke/Meditate.git

**Comment by dliedke** [comment]
https://github.com/dliedke/Meditate/blob/b0973d63de63dfa59ed0d3a7e9f3719df6b3f8f3/Meditate/source/activity/MeditateActivity.mc#L71

**Comment by dliedke** [comment]
You may also try a full clean reinstall of the app in the watch, sometimes Connect IQ mobile damage the config files for the application. I think it worth a try.

1) Remove completely app from watch
2) Use Garmin express with cable to change the activity name
3) Test it again

Sorry about the inconvenience.

**Comment by robcsi** [comment]
No problem at all, and thanks for the help.

Yes, I tried uninstalling too, still the same issue. Maybe the config is cached...? Not sure how these things works.

One question, though: I set a few of the meditations to Meditation activity type. Is that ok, or they should be Yoga?

**Comment by robcsi** [comment]
As I see from the code the default value of meditateYogaActivityName is "Meditating", but I always get "Meditation", even with 'M [time]' set, so something is cached in some way. Even after uninstall/reinstall.

**Comment by robcsi** [comment]
I tested some more:
 - the bug happens only if I changed the activity type of any of the presets to Meditation
 - if the activity type is left as default, Yoga, then the title is applied as in the settings
 - setting the Global Settings/New Activity Type to Meditating, doesn't fix it either

**Comment by dliedke** [comment]
Oh, default activity type in version 8.1 is Meditation. Seems you have cached version of app configuration. I would recommend a hard reset, the watch system configuration should be backed up/restored in Garmin Connect.

**Comment by robcsi** [comment]
I see, my feeling about something being cached was right, then. :)

You mean a hard reset of the watch?

**Comment by robcsi** [comment]
But after an uninstall/reinstall of the app, its default config seems to be used, because the title value is empty in Garmin Connect IQ...

What happens when an app is uninstalled? Is its config cached, or the application itself is, for possible future reinstallation?

**Comment by dliedke** [comment]
In my watch, I had the activities configured as Yoga. I removed the app, reinstalled and they changed correctly to Meditation. The app config should be removed when app is really uninstalled from watch.

**Comment by dliedke** [comment]
> I see, my feeling about something being cached was right, then. :)
> 
> You mean a hard reset of the watch?

https://www8.garmin.com/manuals-apac/webhelp/forerunner255series/EN-SG/GUID-451837E3-6D89-437B-AFE3-46F88950A730-9996.html

**Comment by robcsi** [comment]
An update just arrived for the Forerunner 255. I'll do some more testing.

Thanks for the effort so far.
