### ISSUE TITLE
Requires update but device is already updated (Epix Gen2 pro)

### ISSUE THREAD

**Issue by alvorithm** [dliedke/Meditate#12]
Hi,

When trying to download the excellent app (was an avid user of @vtrifonov-esfiddle's) I receive the following message

"This app requires an update of your Device. Please use [Garmin Express](https://software.garmin.com/en-US/express.html) to update your Device."

I am running the latest version, updated from the watch itself (Version 12.74, 8 Sept 2024), as reported by Garmin Connect. I unfortunately cannot get Garmin Express to detect my watch, even under Win 11.

Can the app be used on an Epix Gen2 pro without Garmin Express? What could be causing the problem?

Thank you so much @dliedke

**Comment by dliedke** [comment]
Hello, are you enabling MTP when watch is connected to PC with USB cable? I have same setup and it works fine here without any drivers

**Comment by dliedke** [comment]
>Can the app be used on an Epix Gen2 pro without Garmin Express?

Yes, I use with the same device, Garmin Express is required if you want to change activity name. Connect IQ mobile can be used for application version update, but not for activity name configuration

**Comment by alvorithm** [comment]
Thank you @dliedke, it's great to know that you're on the same hardware. I was trying to download from Garmin connect (web version). I followed your advice and installed successfully from the mobile app. 

PS. I am out of luck with Garmin express, regardless of whether I use MTP or not (tried many times, followed internet advice re. cables, waiting times, uninstall-reinstall, etc). I will live without changing the activity name.

**Comment by dliedke** [comment]
Oh, did you try another computer? Soft reset the watch? 

https://support.garmin.com/en-US/?faq=Wkf9e0fPST0gP0KoM63DK9#:~:text=Try%20a%20different%20USB%20port,using%20a%20PowerShare%20USB%20port.

**Comment by dliedke** [comment]
Good news, I changed activity name with Connect IQ mobile and it worked 😃😃
