### ISSUE TITLE
Constant audio readout of how many miles travelled 

### ISSUE THREAD

**Issue by Luke3525** [dliedke/Meditate#15]
Hi 
I have a Garmin forerunner 265. When using this app, My phone (Google pixel 8a) will say something along the lines of the following:
"Distance travelled, 0.0 miles"
It does this every 60 seconds throughout my meditation which renders it unusable for me.
I have tried silencing my phone and it still reads it out!

**Comment by dliedke** [comment]
Turn off Bluetooth in the watch. 

Thanks!
