### ISSUE TITLE
Can't save breathworking as New activity 

### ISSUE THREAD

**Issue by mevaere** [dliedke/Meditate#2]
In global settings, changing new activity to Breathworking doesn't change the new activity type. It's style yoga type.

Kind regards, thanks for your app

Watch : Fenix 6x pro firmware 25.0

**Comment by dliedke** [comment]
Are you creating a new session after changing the global settings? The global settings for activity type are for new sessions. The existing pre-configured sessions are Yoga type unless you change them. I tested here and it is working as expected. Thanks!

**Comment by mevaere** [comment]
Thanks it works. You are right. I was expecting breatworking with pre-configured sessions.

Thanks a lot, have a nice day
