### ISSUE TITLE
Crash when changing setting in IQ Connect

### ISSUE THREAD

**Issue by mevaere** [dliedke/Meditate#3]
Hello,

When I change the activity name in setting (iq connect app on android) the app crash when selected on the watch. (Fenix 6x pro fw 25.0)

Thanks for all

**Comment by dliedke** [comment]
Yes, this a problem with Garmin, please use Garmin Express to change activity default name. Several people reported same issue for other apps in Garmin forum but it was not fixed. Thanks!
