### ISSUE TITLE
Combatibility - Instinct 2 series?

### ISSUE THREAD

**Issue by AnonJohn** [dliedke/Meditate#6]
Hi — The Instinct 2 (and 2X, etc) series supports Connect IQ >= 3.0 (I think; they are new watches that definitely support ConnectIQ). Any chance they could be added to the compatibility list? They do have more limited displays, so that might not be trivial. Hoping it is though! The app looks great!

**Comment by dliedke** [comment]
Hello @AnonJohn please use the Meditate Instinct version at https://apps.garmin.com/en-US/apps/45829a6e-f247-4261-9ae6-8587f557f397

There is not enough app memory device for the full meditate app to work on Instinct 2 watches, I already tested that and created the smaller version.

Thank you!

**Comment by AnonJohn** [comment]
Many thanks. I appreciate the work, information, and quick resolution. Will try the other app!
