### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by stefangweichinger** [dliedke/Meditate#7]
Just a quick "thank you"! I started to use your application to track my meditation sessions and find it very useful.
I still might learn more about the HRV features .. so far I use only one (adapted) session setting and I am happy with it.

What I plan to set up for me: a profile with (for example) 3x25min of sitting with 5 minutes pauses inbetween (walking pauses). I assume that shouldn't be hard to set up as soon as I take the time ;-)

regards, Stefan

**Comment by dliedke** [comment]
Thanks Stefan for the nice words! You may also use multi-session feature if you want. HRV is really a complex science and the app has a lot of metrics the original author created that are kind of hard to understand. Have fun with the Meditate app 🙏
